### ISSUE TITLE
Upgrade to Python 3

### ISSUE THREAD

**Issue by thirdformant** [The-Silverwood-Institute/Recibase#16]
Python 2 is now deprecated, so we should switch to Python 3. EstherJ seems to work fine as-is, but I haven't checked the `app.py` in the frontend yet. Nor the tests...

**Comment by kittsville** [comment]
Heroku, our hosting provider, are dropping Python 2 support:

> On January 1st, 2020, Python 2 reached its community designated end of life. Here are a few things that you should know:
> 
> Python on Heroku
> Python 2.7.17 will be available for use on Heroku for the lifetime of the Heroku 18 stack, through April 2023. It will not be made available on Heroku 20.
> 
> Sunsetting Python 2 Support
> Due to the potential security risks, Heroku will be deprecating official support for Python 2.7. As of February 4th, 2021, Python 2 will be completely unsupported on the platform. Python 2.7 apps currently running on Heroku will continue to build and run after that time, but they will not be entitled to platform support. For more information about Heroku’s support policy, see our Support Policy Dev Center Article.
> 
> Heroku is ending security support for Python 2 because the Python core team has ended support for it as well. Our records indicate you have one or more apps currently running Python 2 on Heroku. We take security very seriously, and we know you do too, so we want to help you migrate to a runtime that is more secure by providing options to move forward.

**Comment by kittsville** [comment]
This would affect web.py. EstherJ is ran on Travis.

**Comment by kittsville** [comment]
Done in:
https://github.com/The-Silverwood-Institute/Frontend/commit/e46fbfe7953d0b80996551440d2ac0962dec3bcf
