### ISSUE TITLE
License

### ISSUE THREAD

**Issue by kassner** [The-Silverwood-Institute/Recibase#261]
Hi!

What is the [license](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository) for this project?

Thank you.

**Comment by kittsville** [comment]
Fair point, I forgot to add one. I've added the Apache v2 licence to the [frontend](https://github.com/The-Silverwood-Institute/Frontend/commit/c4e147bc84a086e1844d96a8881cf9551183b36b) and [backend](https://github.com/The-Silverwood-Institute/Recibase/commit/9cf77602dd3285f54c22acd826b9c010602bfb56). The [recipe Chooser](https://github.com/The-Silverwood-Institute/Chooser) side project is licensed MIT as it was based on my standard webapp template that includes a license. Lmk if you have any issues

**Comment by kassner** [comment]
Thank you.
