### ISSUE TITLE
Delete database if it already exists

### ISSUE THREAD

**Issue by thirdformant** [The-Silverwood-Institute/Recibase#8]
Given Recipe databases are disposable it'd be nice if Recibase overwrote any database at the location it's outputting to. This would save having to delete it locally every time you regenerate the db.

Checks that the location given is in fact a database would be sensible. Also the old db can't be reused in case the schema has changed.

**Comment by kittsville** [comment]
Added optional `--overwrite-db` flag. Should make development easier.

Btw, the more untested logic that ends up in main the more nervous I get :mask: 
Deffo need to add integration tests (#10) some time.
